data_sources:
  ofgem_annex_4: "https://www.ofgem.gov.uk/sites/default/files/2024-08/Annex_4_-_Policy_cost_allowance_methodology_v1.19%20%281%29.xlsx"
  ofgem_annex_9: "https://www.ofgem.gov.uk/sites/default/files/2024-08/Annex_9_-_Levelisation_allowance_methodology_and_levelised_cap_levels_v1.3.xlsx"

data_downloads:
  annex: "PROJECT_DIR/inputs/data/raw/"
  archetypes: "PROJECT_DIR/asf_levies_model/config/"
